"use client";

import { useState } from "react";
import { Search, UserPlus, ArrowRight, UserCheck, X } from "lucide-react";
import { useStore, Customer } from "@/store/useStore";
import { useRouter } from "next/navigation";

export default function CheckinPage() {
  const router = useRouter();
  const customers = useStore(state => state.customers);
  const addCustomer = useStore(state => state.addCustomer);
  const setActiveCustomerForSale = useStore(state => state.setActiveCustomerForSale);
  
  const [search, setSearch] = useState("");
  const [isAnonModalOpen, setIsAnonModalOpen] = useState(false);
  const [anonData, setAnonData] = useState({ name: "", phone: "" });
  
  // Track checked in users locally
  const [visitors, setVisitors] = useState<{id: number, name: string, time: string, status: string}[]>([]);

  // If search is empty, show all active customers, otherwise filter by search
  const displayCustomers = search.length > 0 
    ? customers.filter(c => c.name.toLowerCase().includes(search.toLowerCase()) || c.phone.includes(search))
    : customers.filter(c => c.status === "Ativo"); // Show active ones by default

  const handleCheckin = (customer: Customer) => {
    setVisitors(prev => [{
      id: Date.now(),
      name: customer.name,
      time: new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }),
      status: customer.totalVisits > 0 ? "Recorrente" : "Novo"
    }, ...prev]);
    setSearch("");
    setActiveCustomerForSale(customer);
    router.push('/pdv');
  };

  const handleAnonymousCheckin = (e: React.FormEvent) => {
    e.preventDefault();
    if (!anonData.name) return;

    // Save them to the CRM so they are not anonymous anymore
    const newCustomer = {
      name: anonData.name,
      phone: anonData.phone,
      email: "",
      status: "Ativo" as const,
      lastVisit: new Date().toLocaleDateString('pt-BR'),
      totalVisits: 1
    };
    
    addCustomer(newCustomer);
    
    // We need the ID generated by the store, but since we know it just pushes, 
    // we can pass a faux ID or retrieve it. For simplicity, we just pass the object
    setActiveCustomerForSale({ ...newCustomer, id: Date.now() });

    setVisitors(prev => [{
      id: Date.now(),
      name: anonData.name,
      time: new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }),
      status: "Novo"
    }, ...prev]);

    setIsAnonModalOpen(false);
    setAnonData({ name: "", phone: "" });
    router.push('/pdv');
  };

  return (
    <main className="p-8 max-w-5xl mx-auto w-full relative h-screen overflow-y-auto">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Check-in Rápido</h1>
          <p className="text-muted-foreground mt-1">
            Registre a entrada de clientes ou visitantes instantaneamente.
          </p>
        </div>
        <button onClick={() => setIsAnonModalOpen(true)} className="bg-primary hover:bg-primary/90 text-primary-foreground px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors">
          <UserPlus className="w-5 h-5" />
          Visitante Não Cadastrado
        </button>
      </div>

      <div className="bg-card border border-border rounded-xl shadow-sm p-8 mb-8">
        <div className="flex flex-col md:flex-row gap-4 items-center">
          <div className="relative flex-1 w-full">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground w-6 h-6" />
            <input
              type="text"
              placeholder="Pesquisar cliente por nome ou telefone..."
              className="w-full bg-background border border-input rounded-xl pl-14 pr-4 py-4 text-lg focus:outline-none focus:ring-2 focus:ring-primary transition-shadow"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              autoFocus
            />
          </div>
        </div>
        
        <div className="mt-4 border border-border rounded-xl overflow-hidden divide-y divide-border bg-background max-h-64 overflow-y-auto">
          {displayCustomers.map(customer => (
            <div key={customer.id} className="p-4 flex items-center justify-between hover:bg-muted/50 transition-colors">
              <div>
                <p className="font-bold">{customer.name}</p>
                <p className="text-sm text-muted-foreground">{customer.phone}</p>
              </div>
              <button 
                onClick={() => handleCheckin(customer)}
                className="px-4 py-2 bg-secondary text-secondary-foreground font-medium rounded-lg hover:bg-primary hover:text-primary-foreground transition-colors"
              >
                Fazer Check-in
              </button>
            </div>
          ))}
          {displayCustomers.length === 0 && (
            <div className="p-4 text-center text-muted-foreground">
              Nenhum cliente encontrado.
            </div>
          )}
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-8">
        <div>
          <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
            <UserCheck className="w-5 h-5 text-primary" />
            Últimos Check-ins
          </h2>
          <div className="bg-card border border-border rounded-xl shadow-sm divide-y divide-border">
            {visitors.map((visitor) => (
              <div key={visitor.id} className="p-4 flex items-center justify-between hover:bg-muted/50 transition-colors">
                <div>
                  <p className="font-semibold">{visitor.name}</p>
                  <p className="text-sm text-muted-foreground">{visitor.time} • Consumo</p>
                </div>
                <div className="flex items-center gap-3">
                  <span className={`text-xs px-2 py-1 rounded-full font-medium ${
                    visitor.status === 'Novo' ? 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300' : 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900 dark:text-emerald-300'
                  }`}>
                    {visitor.status}
                  </span>
                </div>
              </div>
            ))}
            {visitors.length === 0 && (
              <div className="p-4 text-center text-muted-foreground">
                Nenhum check-in recente.
              </div>
            )}
          </div>
        </div>

        <div>
          <div className="bg-secondary/50 border border-border rounded-xl p-6 h-full flex flex-col items-center justify-center text-center">
            <div className="bg-background p-4 rounded-full mb-4 shadow-sm">
              <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-muted-foreground">
                <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
                <path d="M22 6l-10 7L2 6"></path>
              </svg>
            </div>
            <h3 className="font-semibold text-lg mb-2">Check-in por QR Code</h3>
            <p className="text-muted-foreground text-sm max-w-[250px]">
              Posicione o leitor sobre o código do cliente ou utilize a câmera do tablet.
            </p>
          </div>
        </div>
      </div>

      {/* Modal Visitante Não Cadastrado */}
      {isAnonModalOpen && (
        <div className="absolute inset-0 bg-background/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-card w-full max-w-md border border-border rounded-2xl shadow-2xl flex flex-col">
            <div className="p-6 border-b border-border flex justify-between items-center">
              <h2 className="text-xl font-bold">Check-in de Novo Visitante</h2>
              <button onClick={() => setIsAnonModalOpen(false)} className="p-2 hover:bg-secondary rounded-full">
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <form onSubmit={handleAnonymousCheckin} className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-muted-foreground mb-1">Nome</label>
                <input 
                  type="text" 
                  value={anonData.name}
                  onChange={e => setAnonData({...anonData, name: e.target.value})}
                  required
                  placeholder="Nome do visitante"
                  className="w-full bg-background border border-input rounded-lg px-4 py-2 focus:ring-2 focus:ring-primary focus:outline-none" 
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-muted-foreground mb-1">Telefone (Opcional)</label>
                <input 
                  type="text" 
                  value={anonData.phone}
                  onChange={e => setAnonData({...anonData, phone: e.target.value})}
                  placeholder="(11) 99999-9999"
                  className="w-full bg-background border border-input rounded-lg px-4 py-2 focus:ring-2 focus:ring-primary focus:outline-none" 
                />
              </div>

              <div className="pt-4 flex gap-3">
                <button type="button" onClick={() => setIsAnonModalOpen(false)} className="flex-1 px-4 py-2 rounded-lg font-medium bg-secondary text-secondary-foreground hover:bg-secondary/80 transition-colors">
                  Cancelar
                </button>
                <button type="submit" disabled={!anonData.name} className="flex-1 px-4 py-2 bg-primary text-primary-foreground font-bold rounded-lg disabled:opacity-50 hover:bg-primary/90 transition-colors">
                  Registrar Entrada
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </main>
  );
}
